package com.csv.bit.workshop.students.entity;

public enum Faculty {

    FACULTATEA_DESIGN_DE_PRODUS_SI_MEDIU,
    FACULTATEA_DE_INGINERIE_ELECTRICA_SI_STIINTA_CALCULATOARELOR,
    FACULTATEA_DE_DESIGN_DE_MOBILIER_SI_INGINERIE_A_LEMNULUI,
    FACULTATEA_DE_INGINERIE_MECANICA,
    FACULTATEA_DE_INGINERIE_TEHNOLOGICA_SI_MANAGEMENT_INDUSTRIAL,
    FACULTATEA_DE_SILVICULTURA_SI_EXPLOATARI_FORESTIERE,
    FACULTATEA_DE_STIINTA_SI_INGINERIA_MATERIALELOR,
    FACULTATEA_DE_DREPT,
    FACULTATEA_DE_EDUCATIE_FIZICA_SI_SPORTURI_MONTANE,
    FACULTATEA_DE_LITERE,
    FACULTATEA_DE_MATEMATICA_SI_INFORMATICA,
    FACULTATEA_DE_MEDICINA,
    FACULTATEA_DE_MUZICA,
    FACULTATEA_DE_PSIHOLOGIE_SI_STIINTELE_EDUCATIEI,
    FACULTATEA_DE_SOCIOLOGIE_SI_COMUNICARE,
    FACULTATEA_DE_STIINTE_ECONOMICE_SI_ADMINISTRAREA_AFACERILOR,
    FACULTATEA_DE_ALIMENTATIE_SI_TURISM,
    FACULTATEA_DE_CONSTRUCTII
}
